FROM ubuntu
LABEL authors="stanley@secureailabs.com"
USER root

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    python3 

# GIT
ARG git_personal_token
RUN git config --global url."https://$git_personal_token:@github.com/".insteadOf " https://github.com/"
RUN git clone https://$git_personal_token@github.com/secureailabs/ScratchPad.git /Test
RUN cd /Test
RUN git pull
RUN cd StanleyLin/test_api

CMD ["/bin/bash"]

