FROM ubuntu
LABEL authors="stanley@secureailabs.com"
USER root

# Install dependencies
RUN apt-get update && apt-get install -y git

# GIT
ARG git_personal_token
RUN git config --global url."https://$git_personal_token:@github.com/".insteadOf " https://github.com/"
RUN git clone https://$git_personal_token@github.com/secureailabs/DailyBuilds.git /Daily_builds
# RUN cd /Daily_builds
# RUN git pull

CMD ["/bin/bash"]

