FROM ubuntu
LABEL authors="stanley@secureailabs.com"
USER root

# Install dependencies
RUN apt-get update && apt-get install -y git
# RUN apt-get install -y python3.9
# RUN apt-get -y install pip

# GIT
ARG git_personal_token
RUN git config --global url."https://$git_personal_token:@github.com/".insteadOf " https://github.com/"
RUN git clone https://$git_personal_token@github.com/secureailabs/ScratchPad.git /Test
RUN cd /Test
RUN git pull
# RUN pytest StanleyLin/test_api/sail_api_test.py -m active -sv --junitxml=reports/result.xml

CMD ["/bin/bash"]

