version: "3.5"

services:
  web:
    container_name: test_sail_web
    image: sail-web:local
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./ssl.crt:/app/server/ssl.crt
      - ./ssl.key:/app/server/ssl.key
      - ./.client.env:/app/client/.env
      - ./.server.env:/app/server/.env
